#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "optionparser"
require "green_shed_press"

options = {}
options_parser = OptionParser.new do |opts|
  opts.banner = "Usage: gsp [options]"

  opts.on("-d", "--data [DIRECTORY]", "The directory where the data files are stored") do |directory|
    options[:data_directory] = directory
  end

  opts.on("-o", "--output [DIRECTORY]", "The directory where the output files are stored") do |directory|
    options[:output_directory] = directory
  end

  opts.on("-s", "--server", "Start a server to preview the site") do
    options[:server] = true
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

data_directory   = options[:output_directory] || "./data"
output_directory = options[:output_directory] || "./output"


builder = GSP::Builder.new(data_directory: data_directory, output_directory: output_directory)

build_load_start_time = Time.now
builder.load
build_load_time = Time.now - build_load_start_time

build_start_time = Time.now
builder.build
build_time = Time.now - build_start_time

puts "Load time: #{build_load_time.to_f.round(3)}s"
puts "Build time: #{build_time.to_f.round(3)}s"

if options[:server]
  puts "Starting server at http://localhost:9090"
  root = File.expand_path output_directory
  server = WEBrick::HTTPServer.new :Port => 9090, :DocumentRoot => root
  trap 'INT' do server.shutdown end
  server.start
end